import { util } from 'ele-admin-pro'

const menus = [
    {
      id: 136,
      pid: 0,
      title: 'Dashboard',
      path: '/dashboard',
      component: null,
      menuType: 0,
      authority: null,
      icon: 'home-outlined',
      hide: 0,
    },
    {
      id: 102,
      pid: 101,
      title: '用户管理',
      path: '/system/user',
      component: '/system/user',
      menuType: 0,
      authority: null,
      icon: 'team-outlined',
      hide: 0,
    },
    {
      id: 155,
      pid: 154,
      title: '403',
      path: '/exception/403',
      component: '/exception/403',
      menuType: 0,
      authority: null,
      icon: 'exclamation-circle-outlined',
      hide: 0,
    },
    {
      id: 159,
      pid: 158,
      title: '个人资料',
      path: '/user/profile',
      component: '/user/profile',
      menuType: 0,
      authority: null,
      icon: 'user-outlined',
      hide: 0,
    },
    {
      id: 101,
      pid: 0,
      title: '系统管理',
      path: '/system',
      component: null,
      menuType: 0,
      authority: null,
      icon: 'setting-outlined',
      hide: 0,
      meta: '{"badge":"New", "badgeColor":"#faad14"}',
    },
    {
      id: 137,
      pid: 136,
      title: '工作台',
      path: '/dashboard/workplace',
      component: '/dashboard/workplace',
      menuType: 0,
      authority: null,
      icon: 'desktop-outlined',
      hide: 0,
    },
    {
      id: 138,
      pid: 136,
      title: '分析页',
      path: '/dashboard/analysis',
      component: '/dashboard/analysis',
      menuType: 0,
      authority: null,
      icon: 'bar-chart-outlined',
      hide: 0,
      meta: '{"badge":1}',
    },
    {
      id: 107,
      pid: 101,
      title: '角色管理',
      path: '/system/role',
      component: '/system/role',
      menuType: 0,
      authority: null,
      icon: 'idcard-outlined',
      hide: 0,
    },
    // {
    //   id: 188,
    //   pid: 172,
    //   title: '菜单徽章',
    //   path: '/example/menu-badge',
    //   component: '/example/menu-badge',
    //   menuType: 0,
    //   authority: null,
    //   icon: 'appstore-outlined',
    //   hide: 0,
    // },
    {
      id: 160,
      pid: 158,
      title: '我的消息',
      path: '/user/message',
      component: '/user/message',
      menuType: 0,
      authority: null,
      icon: 'sound-outlined',
      hide: 0,
    },
    
    {
      id: 156,
      pid: 154,
      title: '404',
      path: '/exception/404',
      component: '/exception/404',
      menuType: 0,
      authority: null,
      icon: 'question-circle-outlined',
      hide: 0,
    },
    {
      id: 112,
      pid: 101,
      title: '菜单管理',
      path: '/system/menu',
      component: '/system/menu',
      menuType: 0,
      authority: null,
      icon: 'appstore-outlined',
      hide: 0,
    },
    {
      id: 157,
      pid: 154,
      title: '500',
      path: '/exception/500',
      component: '/exception/500',
      menuType: 0,
      authority: null,
      icon: 'close-circle-outlined',
      hide: 0,
    },
    {
      id: 139,
      pid: 136,
      title: '监控页',
      path: '/dashboard/monitor',
      component: '/dashboard/monitor',
      menuType: 0,
      authority: null,
      icon: 'dashboard-outlined',
      hide: 0,
    },
    {
      id: 187,
      pid: 144,
      title: '用户信息',
      path: '/list/user-info/:id',
      component: '/list/user-info',
      menuType: 0,
      authority: null,
      icon: 'team-outlined',
      hide: 1,
      meta: '{"active":"/list/basic"}',
    },
    {
      id: 122,
      pid: 101,
      title: '字典管理',
      path: '/system/dictionary',
      component: '/system/dictionary',
      menuType: 0,
      authority: null,
      icon: 'profile-outlined',
      hide: 0,
    },
    {
      id: 117,
      pid: 101,
      title: '机构管理',
      path: '/system/organization',
      component: '/system/organization',
      menuType: 0,
      authority: null,
      icon: 'bank-outlined',
      hide: 0,
    },
    {
      id: 154,
      pid: 0,
      title: '异常页面',
      path: '/exception',
      component: null,
      menuType: 0,
      authority: null,
      icon: 'warning-outlined',
      hide: 0,
    },
    {
      id: 158,
      pid: 0,
      title: '个人中心',
      path: '/user',
      component: null,
      menuType: 0,
      authority: null,
      icon: 'control-outlined',
      hide: 0,
    },
    {
      id: 129,
      pid: 101,
      title: '文件管理',
      path: '/system/file',
      component: '/system/file',
      menuType: 0,
      authority: null,
      icon: 'folder-outlined',
      hide: 1,
    },
    {
      id: 127,
      pid: 101,
      title: '登录日志',
      path: '/system/loginlog',
      component: '/system/loginlog',
      menuType: 0,
      authority: 'sys:loginlog:view',
      icon: 'calendar-outlined',
      hide: 0,
    },
    {
      id: 128,
      pid: 101,
      title: '操作日志',
      path: '/system/operlog',
      component: '/system/operlog',
      menuType: 0,
      authority: 'sys:operlog:view',
      icon: 'file-search-outlined',
      hide: 0,
    },
    {
      id: 130,
      pid: 101,
      title: '通知公告',
      path: '/message/notice',
      component: '/message/notice',
      menuType: 0,
      authority: null,
      icon: 'sound-outlined',
      hide: 0,
    },
    {
      id: 135,
      pid: 101,
      title: '用户信息',
      path: '/system/user/info',
      component: '/system/user/info',
      menuType: 0,
      authority: null,
      icon: 'team-outlined',
      hide: 1,
      meta: '{"active":"/system/user"}',
    },
  ]

export const sideMenus = util.toTreeData(menus, 'id', 'pid')
